name: devops-app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python environment 3.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.13
        
      - name: List Files
        run: |
          echo "I hate Joe SOUAID"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

     
     