name: devops-app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python environment 3.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.13
        
      - name: List Files
        run: |
          echo "I hate Joe SOUAID"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install  flake8

      - name: Lint Check
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics

      - name: Test with pytest
        run: |
          python -m pytest -v
        
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps: 
        - name: "Check out branch"
          uses: actions/checkout@v4
        - name: "Docker Login"
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
     
     